# Generated by Django 6.0.2 on 2026-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('wall', 'Wall Tiles'), ('floor', 'Floor Tiles'), ('outdoor', 'Outdoor Tiles')], default='floor', max_length=20),
        ),
    ]
